import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Link from 'next/link'
import { Menu } from 'lucide-react'
const inter = Inter({ subsets: ['latin'] })

import {
  Sheet,
  SheetContent,
  SheetDescription,
  SheetHeader,
  SheetTitle,
  SheetTrigger,
} from "@/components/ui/sheet"

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>

        {/* Header */}
        <header className='flex justify-between px-6 py-4 bg-gray-100 items-center'>
          {/* Left Side */}
          <div>
            <h1 className='text-3xl font-bold text-gray-900'>
              Panaverse
            </h1>
          </div>

          {/* Right Side */}
          <nav>
            <ul className='text-lg font-medium hidden md:flex gap-x-4'>
              <li>
                <Link href={"/"}>Home </Link>
              </li>
              <li>
                <Link href={"/"}>About</Link>
              </li>
              <li>
                <Link href={"/"}>Contact</Link>
              </li>
              <li>
                <Link href={"/"}>Blogs</Link>
              </li>
            </ul>
            <div className='flex md:hidden'>

              <Sheet>
                <SheetTrigger>
                  <Menu />
                </SheetTrigger>
                <SheetContent>
                  <SheetHeader>
                    <ul className='text-lg font-medium gap-x-4'>
                      <li>
                        <Link href={"/"}>Home </Link>
                      </li>
                      <li>
                        <Link href={"/"}>About</Link>
                      </li>
                      <li>
                        <Link href={"/"}>Contact</Link>
                      </li>
                      <li>
                        <Link href={"/"}>Blogs</Link>
                      </li>
                    </ul>
                  </SheetHeader>
                </SheetContent>
              </Sheet>
            </div>
          </nav>
        </header>

        {children}
      </body>
    </html>
  )
}
