import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type IProp = {
  children: React.ReactNode
  seo: React.ReactNode
}

export default function RootLayout({ children }: IProp) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <h1 className='nav_head'>NavBar</h1>
        {children}
        <h1>Footer</h1>
      </body>
    </html>
  )
}
